name: Qodana Code Quality

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: ${{ github.event_name == 'pull_request' }}
          use-caches: true
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_542826521 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'